### ISSUE TITLE
Histórico sem usuário

### ISSUE THREAD

**Issue by CaduGomes** [konecty/Konecty#169]
Os valores de usuário no Histórico estão ficando com valor null nos campos Usuário (que fez a alteração), Criado em e Atualizado em, conforme os prints abaixo.

![image](https://github.com/user-attachments/assets/6b223262-36ba-4d87-8acb-aa3badeda4e5)

![image](https://github.com/user-attachments/assets/294f0083-6843-4545-895f-3f5cf8742e89)

**Comment by 7sete7** [comment]
Fixed on release [2.1.12](https://github.com/konecty/Konecty/releases/tag/2.1.12)
